extends RefCounted
const TaskItem = preload("res://scripts/task_item.gd")  # Preload the TaskItem class

func get_task_items():
	return task_items_array

var task_items_array = [
	TaskItem.new("Make your bed", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Wipe a countertop", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Load one dish", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Sweep a small area", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Throw out expired food", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Fold a towel", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Wipe a mirror", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Sort one item into donation", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Take out the bathroom trash", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Clean one stovetop burner", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Water a plant", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Put away shoes", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Organize a drawer", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Dust a shelf", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Wipe a doorknob", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Change one pillowcase", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Clean sink", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Refill soap dispenser", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Straighten up one room", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Tidy up couch cushions", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Empty lint trap", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Take one item to recycling", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Shake out a rug", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Wipe light switches", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Clean microwave handle", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Sanitize TV remote", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Put one book back", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Wipe table surface", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Sweep under table", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Vacuum a rug corner", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Clean bathroom mirror", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Scrub toilet rim quickly", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Clean fridge handle", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Wipe cabinet door", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Dust picture frame", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Put away groceries", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Throw out old mail", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Tidy up cords", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Stack magazines", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Close open cabinets", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Clean a light bulb", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Push in chairs", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Unclog small drain", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Wipe door frame", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Clean trash can lid", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Sort clean socks", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Hang up towel", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Put remote in place", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Repack a messy bag", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("Clean behind faucet", 30, TaskItem.Category.CHORES, TaskItem.Location.HOME),
	TaskItem.new("10 jumping jacks", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("5 pushups", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Wall sit", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Stretch arms", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Toe touches", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Neck rolls", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Knee lifts", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Arm circles", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Balance on one foot", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("March in place", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Side stretches", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Stand/sit repeatedly", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Mini lunges", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Squat hold", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Jump in place", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Step ups", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Shoulder shrugs", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Hip swings", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Side leg lifts", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Plank hold", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Back stretches", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Wrist circles", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Quick jog in place", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Shadow box", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Dance move practice", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Hamstring stretch", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Tricep dips", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Head tilts", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Deep squat", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Hand stretches", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Finger stretches", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Jog to mailbox", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Calf raises", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Walk around house", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Spin in place", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("High knees", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Heel-to-toe walk", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Elbow stretches", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Quad stretch", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Sit and reach", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Bounce on toes", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Shake limbs", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Clap quickly", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Breath work", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Walk stairs", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Step tap", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Yoga child's pose", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Touch each toe", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Twist torso", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Elbow circles", 30, TaskItem.Category.PHYSICAL, TaskItem.Location.HOME),
	TaskItem.new("Take 3 deep breaths", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Close eyes and relax", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Name 5 things you can hear", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Think of a happy memory", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Look at a nature photo", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Say a mantra", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Smile intentionally", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Count backward from 30", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Picture a peaceful place", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Pet an animal", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Close your eyes for 30 sec", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Write down 1 goal", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Gratitude thought", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Count 3 wins today", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Imagine a color", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Name 5 emotions", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Blink slowly", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Drink water mindfully", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Feel heartbeat", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Self compliment", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Mini meditation", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Visualize success", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Name 3 smells", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Tense and relax hands", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Mini body scan", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Repeat affirmation", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Think of a loved one", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Review calendar", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Plan tomorrow", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Do nothing mindfully", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Hold a soft object", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Name 3 textures", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Close eyes and breathe", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Silently hum", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Look at ceiling quietly", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Scan room slowly", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Count wall objects", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Mindfully sip drink", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Sit in silence", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Journal 1 sentence", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Recall dream", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Smile in mirror", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Plan a reward", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Visualize a tree", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Think of a solution", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Check posture", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Review a value", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Notice your breath", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Sit with emotion", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Whisper calming word", 30, TaskItem.Category.MENTAL, TaskItem.Location.HOME),
	TaskItem.new("Read a word and definition", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Look up a fact", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Watch 30-sec tip video", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Read 1 paragraph of book", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Translate 1 word", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Name a country and capital", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Recall a quote", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Solve a math fact", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Practice spelling", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Say alphabet backwards", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Recite multiplication fact", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Read random wiki fact", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Memorize a short poem line", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Practice tongue twister", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Say planets in order", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Name continents", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Draw quick sketch", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Trace a shape", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Read a news headline", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Recall science fact", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Read proverb", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Look at a map", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Practice saying 'hello' in 2 languages", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Memorize phone number", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Write a synonym", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Spell a hard word", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Name 5 animals", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Describe 1 emotion", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Practice sign language word", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Do 1 flashcard", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Recite birthday", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Learn 1 health tip", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Name body parts in another language", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Quiz self on trivia", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Recall a lesson", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Write down a question", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Visualize a graph", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Say numbers 1–10 in new language", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Think of a cause-effect pair", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Review a habit", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Draw a concept", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Practice a definition", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Spell backwards", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Say 5-letter words", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Repeat tongue twister", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Quick brainstorm list", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Rephrase a sentence", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Watch educational short", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Learn 1 art term", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME),
	TaskItem.new("Define a career", 30, TaskItem.Category.LEARNING, TaskItem.Location.HOME)
]
